### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Aeschylus28** [seansylee/kanban-board-bot#3]
Hey. I can't seem to find the config file anywhere. Could I get some help as to where it is located?

**Comment by mmtmr** [comment]
create a config folder and add botconfig.json under it, the json file contains:
{
	"prefix": "$",
    "botName": "YOUR BOT NAME",
	"token": "YOUR BOT TOKEN"
}

**Comment by seansylee** [comment]
This was fixed with this PR: https://github.com/seansylee/kanban-board-bot/pull/5
